### ISSUE TITLE
No type information are rendered

### ISSUE THREAD

**Issue by sichvoge** [wdullaer/raml2html-slate-theme#11]
None of the type information are actually rendered. I tried JSON schema, XSD, and RAML data types, but don't see these information. Is this a bug or not yet implemented?

**Comment by wdullaer** [comment]
This isn't a bug, it's a known gap in the functionality (it's even part of the TODO section in the README)
I could mention the type name for request and response somewhere in the method descriptions.

Types / schema's tend to become very verbose / complex quickly though and I haven't figured out a nice way to render them yet.
In the original project I had built this for, I just had a general documentation page describing the various types in use, with links to their raw json schema definitions.

**Comment by sichvoge** [comment]
haha - sorry must have missed it. :(
