### ISSUE TITLE
"no such file or directory" after first install and first run

### ISSUE THREAD

**Issue by mgara** [wdullaer/raml2html-slate-theme#19]
Hello, 
I'm receiving this error when I'm trying to run the command for doc generation: 
error: ENOENT: no such file or directory, lstat '/usr/lib/node_modules/raml2html-slate-theme/index.nunjucks'

Steps to reproduce: 
1 - install the raml2html slate theme
2 - run the command to generate the doc 

Env : 
CentOS 7 
RAML 1.0
Nodejs : v6.9.1

ps : I can successfully generate the doc with the default theme

and this is my /usr/lib/node_modules/raml2html-slate-theme/ content : 
```
 ⚡ root@my-sexy-server /usr/lib/node_modules/raml2html-slate-theme  ll
total 28K
-rw-r--r--   1 nobody root 6.0K Jun 25 08:30 index.js
-rw-r--r--   1 nobody root 1.1K May 24 13:06 LICENSE
drwxr-xr-x 129 root   root 4.0K Jul  3 08:59 node_modules
-rw-r--r--   1 nobody root 3.4K Jul  3 08:59 package.json
-rw-r--r--   1 nobody root 3.4K Jun 25 08:30 README.md
drwxr-xr-x   5 nobody root  134 Jul  3 08:59 templates
```

**Comment by mgara** [comment]
more info :  
in file : /usr/lib/node_modules/raml2html/index.js
for some reason it can't find the module 'raml2html-default-theme' 
so it falls back to the exception , when I display the errors and the output of templatesPath I have these two lines : 

the **err** : {"code":"MODULE_NOT_FOUND"}

the "**templatesPath**" : 
**/usr/lib/node_modules/raml2html-slate-theme** which is **wrong** .. as it should be : **/usr/lib/node_modules/raml2html-slate-theme/templates**
```
function getConfigForTheme(theme, programArguments) {
  if (!theme) {
    theme = 'raml2html-default-theme';
  }

  try {
    // See if the theme supplies its own config object (or function that creates this object), and return it
    const config = require(theme);

    // If it's a function then call it with the program arguments
    if (typeof config === 'function') {
      return config(programArguments);
    }

    // Otherwise we assume it's a config object (default behavior)
    return config;
  } catch (err) {
    console.log(JSON.stringify(err))
    // Nope, forward to getConfigForTemplate
    const templatesPath = path.dirname(
      require.resolve(`${theme}/package.json`)
    );
    console.log(templatesPath)
    return getConfigForTemplate(path.join(templatesPath, 'index.nunjucks'));
  }
}
```

After adding the **/templates** directory to the **templatesPath** (1)   OR installing the **raml2html-default-theme** package  with   `npm install -g raml2html-default-theme`   I'm getting this error :  

**(/usr/lib/node_modules/raml2html-slate-theme/templates/index.nunjucks) [Line 1, Column 18]
  Error: Unable to call `getSafeId`, which is undefined or falsey**

(1):   
```
const templatesPath = path.dirname(
      require.resolve(`${theme}/package.json`)
    )+"/templates";

```

**Comment by wdullaer** [comment]
It seems like the theme is not properly loading.
I always install it in the project directory, not globally.
Let me see if I can reproduce this.

**Comment by mgara** [comment]
Oh I'm just using the command line !

```
raml2html \
--theme 'raml2html-slate-theme' \
-o 'path/to/output/file.html' \
-i 'path/to/raml/file.raml'
```

but I'm  willing to integrate this in a project and generate the html with within the CI process.

**Comment by mgara** [comment]
@wdullaer  I would like to contribute actively to this repository, do you have any guidance about setting up the **dev** environment? Thanks.

**Comment by aherranz** [comment]
I am experiencing the same problem:

```bash
$ npm install raml2html raml2html-slate-theme
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
/home/angel/Myproject/ahapidoc/raml
├── raml2html@6.3.0 
└── raml2html-slate-theme@2.0.0 
$ ./node_modules/.bin/raml2html --theme raml2html-slate-theme --logo templates/myproject-logo-s.svg --color-theme templates/_variables_myproject.styl -i myproject_integration_guide_v2.raml -o myproject_integration_guide_v2.html
fs.js:994
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, lstat '/home/angel/Myproject/ahapidoc/raml/node_modules/raml2html-slate-theme/index.nunjucks'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at Object.realpathSync (fs.js:1676:21)
    at getConfigForTemplate (/home/angel/Myproject/ahapidoc/raml/node_modules/raml2html/index.js:49:41)
    at Object.getConfigForTheme (/home/angel/Myproject/ahapidoc/raml/node_modules/raml2html/index.js:129:12)
    at Object.<anonymous> (/home/angel/Myproject/ahapidoc/raml/node_modules/raml2html/bin/raml2html:53:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
Makefile:23: recipe for target 'myproject_integration_guide_v2.html' failed
make: *** [myproject_integration_guide_v2.html] Error 1
```

**Comment by wdullaer** [comment]
I've figured out what's wrong here.
The lib folder does not seem to be published to npm, which causes the loading of the theme to fail.
raml2html overcatches this error and falls back to trying to load a template, which then fails with this error.
