### ISSUE TITLE
Raw JSON at the top of the site

### ISSUE THREAD

**Issue by amitav13** [wdullaer/raml2html-slate-theme#24]
Hi,
I just picked up the plugin and found that it's giving a large blob of JSON sitting right at the top of the site. Not sure what's going on, but I'd be happy to give any more details if it helps.  

![screen shot 2017-08-22 at 10 35 09 pm](https://user-images.githubusercontent.com/7059002/29577859-9cbc5240-878a-11e7-9d83-43b7ae4f6861.jpg)

![screen shot 2017-08-22 at 10 36 30 pm](https://user-images.githubusercontent.com/7059002/29577803-6d61ba26-878a-11e7-98bf-07c8e96d30d7.jpg)

[api.raml.zip](https://github.com/wdullaer/raml2html-slate-theme/files/1242801/api.raml.zip)

**Comment by wdullaer** [comment]
A debug statement I forgot to remove
