### ISSUE TITLE
JSON schema not displayed

### ISSUE THREAD

**Issue by ArtFlag** [wdullaer/raml2html-slate-theme#42]
Hi and thanks for the great work on this theme!

I have an issue with the following raml file:
```
#%RAML 1.0
title: API title
version: v0
documentation:
  - title: API title 2
baseUri: https://stuff.net/v0/d
mediaType: application/json

/import:
  displayName: import displayname
  post:
    description: Creates a some stuff
    body:
      application/json:
        type: !include messages/import_job_post_request.json
    responses:
      201:
        description: |
          Some stuff
        body:
          application/json:
            type: !include messages/import_job_post_response.json
```

I get the following output
![screen shot 2018-05-09 at 16 33 41](https://user-images.githubusercontent.com/25686502/39820722-ca35b6ec-53a6-11e8-8fa7-9b47f81105c1.png)

The schemas are not resolved. 

Is it because they are not in the RAML file itself?
Would it be possible to update the theme so that it digs into the json schema files?

Thanks for the info!

**Comment by ArtFlag** [comment]
Ok my bad, it was only the condition inside the template that was too restrictive for me.

**Comment by wdullaer** [comment]
Sorry for the late reply.
The theme should render schema's even if they're not defined in line. 

Did you get it work?

**Comment by ArtFlag** [comment]
I did, I only had to change the resource nunjuck template. The check 
`{% if ((method.body | length != 0) and hasExamples(method.body)) %}` wouldn't pass since I have no examples. 🙂

**Comment by wdullaer** [comment]
That is an issue, I'll reopen this and have a look to fix it properly
