### ISSUE TITLE
description of response status codes

### ISSUE THREAD

**Issue by KimSchneider** [wdullaer/raml2html-slate-theme#59]
Hey, first of all: great template.

We have descriptions set on our reponse status codes. For example:

```
responses:
                200: 
                    description: |
                        - Returns one job, if any action is required.
                        - Each job contains `jobType`, `jobId` and an `executeTime`.
                        - Jobs can additionally contain a set of requirements (`required`) which must be met before executing the job.
                        - The optional `meta` property contains jobspecific informations.
                204:
                    description: Returns an empty answer, if no jobs are available.
```

Could you display the reponse status codes including description on the right hand side?
We thought of a structure like:

```
CURL Example
...

Response 200
... Description ...

Reponse Body
... Examples ...

Response 204
... Description ...

Reponse Body
... Examples ...
```

If you have a readme or guide on how to add missing parts of the raml specification to the theme, we'd be glad to support you with pull requests, too.

**Comment by wdullaer** [comment]
Hi,

That should be feasible.
This will mostly be managed through the template, which you can find in `templates/resource.nunjucks`
The relevant parts are around line 136

Currently only responses with code 200 and 201 rendered. Since error responses are often shared, this would lead to a lot of repetition.

**Comment by KimSchneider** [comment]
Thanks, fixed everything in a pull request
