### ISSUE TITLE
raml2html-slate-theme doesn't handle markdown in description

### ISSUE THREAD

**Issue by yyamano** [wdullaer/raml2html-slate-theme#72]
Markdown in description is handled as plain text.

Here is a fragment of RAML.

~~~
/users/{id}:
  get:
    queryParameters:
      foo:
        description: |
          blah, blah, blha
          * 1st item
          * 2nd item
        type: string
        required: false
~~~

raml2html-slate-theme generate the following.

<img width="502" alt="screenshot" src="https://user-images.githubusercontent.com/108492/60633643-a387dc00-9e46-11e9-8a06-24f4cdf92e3e.png">

**Comment by yyamano** [comment]
I'm working to fix it on https://github.com/yyamano/raml2html-slate-theme/tree/issue-72
Will send a pull request once done.

**Comment by kmcnerney-salesforce** [comment]
@yyamano can you make the same change for descriptions directly underneath an endpoint? For example:
```
/users/{id}:
   description: |
       blah, blah, blha
       * 1st item
       * 2nd item
   get: ...
```

**Comment by yyamano** [comment]
@kmcnerney-salesforce Thank you for pointing it out. I just sent a pull request.
